### PR TITLE
Update stCard.tsx

### PR DESCRIPTION
**Pull request by OJddJO**
Added `...styles.filter,` to give the possibility to modify Filter style

### CODE REVIEW

**Comment by gamcoh** [comment]
Hi,

Could you give an example of what this is?

**Comment by OJddJO** [comment]
So normally the image of the card is dimmed
image image

With `...styles.filter` added in `/streamlit_card/frontend/src/stCard.tsx`, we can add css for the filter in the `styles` argument
```
from streamlit_card import card

res = card(
    title="Streamlit Card",
    text="This is a test card",
    image="https://placekitten.com/500/500",
    styles={
        "card": {
            "width": "500px",
            "height": "500px",
            "border-radius": "60px",
            "box-shadow": "0 0 10px rgba(0,0,0,0.5)",
            ...
        },
        "filter": {
            "background-color": "rgba(0, 0, 0, 0)"   <- make the image not dimmed anymore
            ...
        }
    }
)
```

**Comment by gamcoh** [comment]
Oh alright great!
Could you please add this information to the readme?
I'll merge right after

**Comment by OJddJO** [comment]
Done !

**Pull request merged**
